python:
  - 3.6
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
vc:                            # [win]
  - 14.1                       # [win]
channel_sources:
  - ramonaoptics,conda-forge,defaults
channel_targets:
  - ramonaoptics main
